### ISSUE TITLE
Add support for custom transition-property

### ISSUE THREAD

**Issue by sahat** [acss-io/atomizer#238]
Right now `Trsp` seems to work only with `a` argument (*all*). So, if you need to implement other transition properties like `border-color`, `color`, `font-weight`, it won't work.

So here are my suggestions:

1. Add custom arguments similar to [`Trstf`](https://github.com/yahoo/atomizer/blob/master/src/rules.js#L2531-L2538): `bdc`, `c`, `fw`, etc.
2. Allow actual transition properties as they would be displayed in CSS: `Trsp(border-color)` or `Trsp(font-weight)` or `Trsp(background-color)`. However, I am not sure if this will cause an ambiguity on whether you meant a *transition property* or a *custom variable*.

Source: https://github.com/yahoo/atomizer/blob/master/src/rules.js#L2510

**Comment by src-code** [comment]
Hi @sahat, that's right - `Trsp` requires you to use a custom variable rather than providing the values as arguments, due to the potential for ambiguity.  Providing all the possible properties that one might transition seems like it could be difficult to maintain, so I'm not sure we'd want to go that route.  (Actually, I'd be interested to see a list of animatable properties across browsers...I'm curious exactly how many there are!)  

For now you can achieve what you need by using a custom variable - that also means you can list multiple properties as the spec allows, which can be helpful.

**Comment by soluml** [comment]
If it only works with `a` the reference needs to be updated as it specifies you can use a <value> or <custom-param>.

**Comment by src-code** [comment]
@soluml Good point!  Will have to update the rule for that.
