### ISSUE TITLE
Uppercase hex values are silently ignored

### ISSUE THREAD

**Issue by src-code** [acss-io/atomizer#246]
From @thierryk:

> Today, the class `Bgc(#0280AE.5)` produces this style: `background-color: #028;`. But I think it should fail as it uses uppercase letters.

I believe we disallowed uppercase letters in order to avoid a scenario where mixed case would lead to duplicate styles being created with slightly different selectors.  If we're going to continue disallowing uppercase in hex values, then it seems like they should at least throw a warning, if not break outright.  (Since the resulting CSS is not correct.)  Or perhaps we allow uppercase but throw a warning?  I might prefer that approach, actually...

Thoughts?  @renatoi @dnewcome

**Comment by dnewcome** [comment]
Ideally I think we'd want to accept upper or lower case and normalize the generated CSS rule to one or the other.

That probably complicates things since we use the same code paths (I think) for other case-sensitive values. I think we should generate a warning at the very least giving the generated CSS. We could support mixed case in the future, or change the warning to an error and that's the end of it.

**Comment by src-code** [comment]
The problem with normalizing it automatically is that we'd have to modify the markup as well, otherwise the classes won't match the selectors and the CSS will be broken.  So I'm inclined to support case-sensitive hex values, but throw a warning if they're detected, that way at least we're not introducing subtle bugs in the CSS, but we're also pushing developers to optimize their code further.

**Comment by samlecuyer** [comment]
This is somewhat fixed by #263

**Comment by thierryk** [comment]
Fixed by https://github.com/acss-io/atomizer/pull/263
