### ISSUE TITLE
"Cnt" supports <value> or <custom-param> but doesn't seem to work with empty string: ""

### ISSUE THREAD

**Issue by soluml** [acss-io/atomizer#270]
Hello, I'm trying to create an empty presentation pseudo element with `content: '';`. According to the reference, I should be able to use `Cnt('')::b`/`Cnt("")::b`, but neither seem to generate the above css.

Is there a trick I'm missing, or do I need to manually create this rule in my stylesheet?

Thanks!

**Comment by soluml** [comment]
Actually, I'm not sure I can get the content property to work at all with a pseudo element. Any random string I've tried (both quoted and not) doesn't seem to work.

**Comment by thierryk** [comment]
I don't think pseudos work. Pinging @src-code and @renatoi to confirm this.

**Comment by soluml** [comment]
Pseudo elements work with other props using the [right selector](https://github.com/acss-io/atomizer/blob/master/src/lib/grammar.js#L42).  `W(100%)::b`, `H(100%)::b`, `Pos(a)::b` are all working for me. <value>'s just don't seem to work with the content property and/or with pseudo's, which is weird since the content property is exclusively for pseudo elements.

**Comment by thierryk** [comment]
@soluml ok, no wonder I could not reproduce this using the [online tool](https://pankajparashar.com/atomizer-web/) as it is using Atomizer v3.2.1 while support for this is from [v3.3.0](https://github.com/acss-io/atomizer/releases/tag/v3.3.0).
So, in this case, my question is: did you try `Cnt()::b`? Without `'` or `"` isnide the `()`.

**Comment by soluml** [comment]
Yea `Cnt()::b` doesn't produce anything. Doesn't spit out any errors, it's just ignored. I also tried `Cnt(attr(data-test))::b` thinking that maybe it's expecting attr() and it didn't work.

I tried `Cnt(n)` and `Cnt(n)::b` in latest and both worked as expected.

Basically as it is today, it seems like `Cnt` ignores any `<value>` or `<custom-param>` (when supplied with the `::b` flag) but will work with the supplied defaults in the reference.  I haven't familiarized myself enough with the source to make any sort of pull request, but `Cnt` should probably work exactly like `W` or `H`.  Anything passed in should be written to the content property because you can have some really crazy combinations:

```@media print {
     #main-content a[href]:after { " (" attr(href) ") "; }
}```



I hadn't seen that Online Tool, thanks for that.  Using it, the `Cnt` property is ignored entirely, with or without pseudo's, so it looks like `Cnt` must be new to Atomizer as well which makes sense since it's only used with pseudo's.

**Comment by thierryk** [comment]
Hopefully @src-code will look at this issue soon, but for the record I've never been a fan of supporting *pseudo-selectors* because this is like Pandora's box. 

For example:

> Anything passed in should be written

I don't see how that could work at there are many challenges there (white space, quotes, etc.)  

> I also tried `Cnt(attr(data-test))::b`

Not sure if @src-code has considered this (nested parentheses) when implementing `Cnt`(?)

As a side note, I don't think all styles should be "*atomized*", I think there are cases where following a classic approach makes more sense...

**Comment by renatoi** [comment]
It seems that `Cnt` was introduced later in 3.3.0. Honestly, I'm not very familiar with its usage and syntax. But I can have a good idea looking at the diff. It's also a good place to look if you want to submit a PR to fix this issue:

https://github.com/acss-io/atomizer/pull/244/files

To @thierryk 's point, I remember that, initially, we thought of leaving `content` to be written directly in css files (not in atomic classes) because it usually does not give much benefit of being reused everywhere. Actually, pseudo elements as a whole. Not everything needs to be atomic classes, some things might make sense to leave as normal css classes. It usually comes down to preference I guess, but I like to have a mix of both in my projects.

A few examples of things that we decided to leave outside of atomic classes are helper classes. They have CSS properties that usually go together all the time no matter what, so we just create a normal css class for it.

See: http://acss.io/guides/helper-classes.html

**Comment by soluml** [comment]
I think leaving the Content property out of Atomizer makes a lot of sense and that's how I'm currently skirting around this issue. That said, it seems that if `Cnt` is in Atomizer than it should at least support empty string as a value either as a default value or custom param.

It's hard to say with any sort of certainty without hard data, but personally, 9 times out of 10 I'm using Pseudo Elements for presentation and set `content: '';`.

Seems like that could be as simple as adding an [argument here](https://github.com/acss-io/atomizer/blob/master/src/rules.js#L885), something like `"'": "''"`, `"e": "''"` or `"empty": "''"` perhaps?

**Comment by src-code** [comment]
Yeah, `content` is kind of a tricky one.  It's not very useful without custom values, at which point maybe you're better off not doing it in atomic.  But using `content` with empty values (or a dummy value like `.`) is a common pattern, so maybe it makes sense to add some arguments as @solumi suggests.  Not sure though how far down the rabbit hole we really want to go with this though, as no other class offers such predefined values that aren't in the spec.  Thoughts, @renatoi and @thierryk?

**Comment by thierryk** [comment]
To be honest, I don't really see value in supporting pseudo-elements&mdash;even less `::before` and `::after`. For the same reason, I don't see a need for `content`.

**Comment by soluml** [comment]
I think I'm going to go ahead and mark this closed.  What I was originally trying to accomplish can be done fairly easily by adding something like this to the AtomizerConfig `custom: { emptyquote: '""' },` and then using this as your class: `Cnt(emptyquote)::b`.
