### ISSUE TITLE
Atomizer requires quoted attribute values

### ISSUE THREAD

**Issue by fidian** [acss-io/atomizer#280]
I am processing my HTML through a minifier and it prefers to remove unnecessary quotes.  Unnecessary, in this case, means anywhere a browser doesn't require a quote to exist.

`test.html`:

    <div class="Fl(end)"></div>
    <div class=Fl(start)></div>

Running `atomizer test.html`:

    Parsing file test.html for Atomic CSS classes

    .Fl\(end\) {
      float: right;
    }

It is missing the `.Fl(start)` rule.

I'm going to have to run atomizer before I minify HTML, which is pretty obvious.  However, shouldn't Atomizer work with minified HTML as well?

**Comment by tom76kimo** [comment]
Ideally, it should be. Will look into it.

**Comment by tom76kimo** [comment]
Maybe fix this line https://github.com/acss-io/atomizer/blob/master/src/lib/grammar.js#L63

**Comment by src-code** [comment]
Atomizer doesn't care about HTML syntax - you can parse any text file for Atomic classnames.  But as @tom76kimo pointed out, the regex does look for "boundary", which includes things like curly braces, whitespace, and quotes.  So in your case, it's not matching between `=` isn't currently a valid boundary character.  The question then is, would it break anything if we allowed `=` to be treated as a boundary... 

cc @renatoi

**Comment by renatoi** [comment]
If I remember correctly, the boundary is there to put a stop to the search for parent selectors because its name is arbitrary, for example: `parent_Fl(end)` we wouldn't know when to stop looking for the parent selector. So the boundary serve as a stop mark. I believe adding `=` would only break if someone uses it as a class name for a parent selector such as `<div class="=parent_Fl(end)">` which is unlikely but since this is an assumption it might be safer to bump major.

**Comment by src-code** [comment]
I'm going to treat this as a WONTFIX for now, since as @renatoi points out, `=` could be a valid class char if escaped.
